#!/bin/bash

FUNNAME=$1
CONTENT=

if [ -z "$FUNNAME" ]
then
    FUNNAME=$(pbpaste | perl -n -e'/pub fn ([^(]+)/ && print $1')
    CONTENT=$(pbpaste)
fi

test -z "$FUNNAME" && exit

DIR="src/$FUNNAME"
test -e "$DIR/mod.rs" && exit
echo "Creating code snippet for ${FUNNAME}..."
mkdir -p "$DIR"

cat > "$DIR/mod.rs" <<EOF
mod solution;
#[cfg(test)]
mod tests;
EOF

cat > "$DIR/tests.rs" <<EOF
use crate::*;

#[test]
fn case_1() {
    // Solution::$FUNNAME
    todo!();
}
EOF

if [ -z "$CONTENT" ]
then
    cat > "$DIR/solution.rs" <<EOF
use crate::*;

impl Solution {
    pub fn $FUNNAME() {
        todo!();
    }
}
EOF
else
    cat > "$DIR/solution.rs" <<EOF
use crate::*;

${CONTENT/\}/todo!();}
}
EOF
fi

grep "\<$FUNNAME\>" src/lib.rs > /dev/null || echo "pub mod $FUNNAME;" >> src/lib.rs
rustfmt src/lib.rs
